# Generated by Django 4.1.6 on 2023-02-06 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArSecc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accesos.area')),
                ('Seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accesos.seccion')),
            ],
            options={
                'verbose_name_plural': '--> ArSecc',
            },
        ),
        migrations.AlterField(
            model_name='area',
            name='Seccion',
            field=models.ManyToManyField(blank=True, through='accesos.ArSecc', to='accesos.seccion'),
        ),
    ]
