# Generated by Django 4.1.6 on 2023-02-06 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0002_caracc_cargo_caracc_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accesos.acceso'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fechaRetiro',
            field=models.DateField(blank=True, verbose_name='Fecha de Retiro'),
        ),
    ]
