# Generated by Django 4.1.6 on 2023-02-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0002_arsecc_alter_area_seccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='Seccion',
            field=models.ManyToManyField(to='accesos.seccion'),
        ),
    ]
