# Generated by Django 4.1.6 on 2023-02-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0003_alter_area_seccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='Seccion',
            field=models.ManyToManyField(blank=True, through='accesos.ArSecc', to='accesos.seccion'),
        ),
    ]
