# Generated by Django 4.1.6 on 2023-02-06 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0003_alter_persona_cargo_alter_persona_fecharetiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accesos.cargo'),
        ),
    ]
