# Generated by Django 4.1.6 on 2023-02-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0004_alter_persona_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fechaRetiro',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Retiro'),
        ),
    ]
