# Generated by Django 4.1.6 on 2023-02-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0005_alter_persona_fecharetiro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acceso',
            options={'verbose_name_plural': '3.- Acceso'},
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name_plural': '1.- Area'},
        ),
        migrations.AlterModelOptions(
            name='arsecc',
            options={'verbose_name_plural': 'ArSecc'},
        ),
        migrations.AlterModelOptions(
            name='caracc',
            options={'verbose_name_plural': 'Secc_Acc'},
        ),
        migrations.AlterModelOptions(
            name='secacc',
            options={'verbose_name_plural': 'Secc_Acc'},
        ),
        migrations.AlterModelOptions(
            name='seccion',
            options={'verbose_name_plural': '2.- Seccion'},
        ),
        migrations.AddField(
            model_name='persona',
            name='usr',
            field=models.CharField(default='', max_length=10, verbose_name='Usuario'),
        ),
    ]
