# Generated by Django 4.1.6 on 2023-02-07 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0006_alter_acceso_options_alter_area_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secacc',
            options={},
        ),
    ]
