# Generated by Django 4.1.6 on 2023-02-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0007_alter_secacc_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caracc',
            options={'verbose_name_plural': 'Accesos'},
        ),
        migrations.AlterField(
            model_name='persona',
            name='fechaIngreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso'),
        ),
    ]
